### Exercise 10: Boolean Masking & Iteration

**Requirements:**
1. Generate an array `dataset = np.arange(1, 21).reshape(2, 10)` to simulate imported 2D data.
2. Extract all elements that are strictly greater than `10`.
3. Test column-wise whether **any** value in each column exceeds `15`.
4. Extract all elements that satisfy two conditions simultaneously: strictly greater than `5` AND strictly less than `10`.
5. Given a 3D array of shape `(2, 2, 3)`, iterate through every single individual number in sequence using an iterator tool rather than 3 nested loops.

<details>
<summary>💡 Need a hint?</summary>

- Filter by condition: `arr[arr > 10]`
- Column-wise test: `np.any(condition, axis=0)`
- Bitwise multi-condition: `arr[(condition1) & (condition2)]`
- Flat N-D iteration: `for item in np.nditer(arr_3d): ...`
</details>

----------

1. Generate an array `dataset = np.arange(1, 21).reshape(2, 10)` to simulate imported 2D data.

In [2]:
import numpy as np

dataset = np.arange(1, 21).reshape(2, 10)
dataset

array([[ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15, 16, 17, 18, 19, 20]])

2. Extract all elements that are strictly greater than `10`.

In [4]:
a1 = dataset[dataset>10]
a1

array([11, 12, 13, 14, 15, 16, 17, 18, 19, 20])

3. Test column-wise whether **any** value in each column exceeds `15`.

In [11]:
a2 = np.any(dataset>15, axis=0)
a2

array([False, False, False, False, False,  True,  True,  True,  True,
        True])

4. Extract all elements that satisfy two conditions simultaneously: strictly greater than `5` AND strictly less than `10`.

In [17]:
a3 = dataset[((dataset>5) & (dataset>10))]
a3

array([11, 12, 13, 14, 15, 16, 17, 18, 19, 20])

5. Given a 3D array of shape `(2, 2, 3)`, iterate through every single individual number in sequence using an iterator tool rather than 3 nested loops.

In [38]:
D_array = np.arange(1,13, 1).reshape(2,2,3)

print('Initial Array: ', D_array)

print('--------')


'''
for x in D_array:
    print(x)
    for y in x:
        print(y)
        for z in y:
            print(z)    
'''
for x in D_array:
    for y in x:
        for z in y:
            print(z)    


Initial Array:  [[[ 1  2  3]
  [ 4  5  6]]

 [[ 7  8  9]
  [10 11 12]]]
--------
1
2
3
4
5
6
7
8
9
10
11
12
