### Exercise 2: Slicing & Updating 2D Matrices

**Given the following 2D array:**
```text
[[ 1,  2,  3,  4,  5,  6,  7],
 [ 8,  9, 10, 11, 12, 13, 14]]
```

**Requirements:**
1. Extract the number `10` using explicit `[row, column]` index coordinates.
2. Extract the number `14` using negative index positioning.
3. Extract values `2` through `6` from the first row using range slicing.
4. Extract every second value across the entire first row (`[1, 3, 5, 7]`) using step slicing.
5. Extract the entire second column across both rows (`[2, 9]`).
6. Perform the following in-place updates:
   - Replace the value at `[0, 0]` with `100`.
   - Replace every value in the last column with `700`.
   - Replace the second-to-last column with the array `[600, 1300]`.

<details>
<summary>💡 Need a hint?</summary>

- **Target a single cell:** `array[row_index, col_index]`
- **Negative coordinate:** `array[row_index, -1]`
- **Row range slice:** `array[row_index, start:stop]`
- **Step slicing:** `array[row_index, ::step]`
- **Entire column across all rows:** `array[:, col_index]`
- **Batch column overwrite:** `array[:, col_index] = [value1, value2]`
</details>

Extract the number 10

In [11]:
import numpy as np

a = np.array( [ [1, 2, 3, 4, 5, 6, 7] , [6, 9, 10, 11, 12, 13, 14] ] )

a[1,2]

np.int64(10)

Extract the number 14 using backwards/negative coordinates

In [6]:
a[1,-1]

np.int64(14)

Extract values 2 through 6 from the first row

In [7]:
a[0, 1:-1]

array([2, 3, 4, 5, 6])

Extract every second number from the first row starting at the beginning

In [8]:
a[0,::2]

array([1, 3, 5, 7])

Extract the entire second column across both rows

In [9]:
a[:,1]

array([2, 9])

Update the first element to 100, replace the entire last column with 700, and replace the second-to-last column with [600, 1300]

In [23]:
# Let's turn 1st element to 100
a[ [0] , [0] ] =  100
print(a)

print('----------')

# Now let's turn last column to 700s
a[ :,-1 ] =  700
print(a)

print('----------')

# Now let's replace the second-to-last column with [600, 1300]
a[ [0, 1] , [-2, -2] ] = [600, 1300]
print(a)

[[ 100    2    3    4    5  600  700]
 [   6    9   10   11   12 1300  700]]
----------
[[ 100    2    3    4    5  600  700]
 [   6    9   10   11   12 1300  700]]
----------
[[ 100    2    3    4    5  600  700]
 [   6    9   10   11   12 1300  700]]
