### Exercise 3: 3D Arrays & Coordinate-Based Indexing

**Requirements:**
1. Build a 3D array of shape `(2, 2, 2)` containing numbers `1` through `8`.
2. Retrieve the element `4`.
3. Extract the sub-blocks `[[3, 4]]` and `[[7, 8]]` across all depth layers.
4. Overwrite those selected blocks with `[[30, 40], [70, 80]]`.
5. On the 2D array `sample = np.array([[1,2,3,4,5,6,7], [8,9,10,11,12,13,14]])`:
   - Use list coordinates to grab `2` and `13` simultaneously in one query.
   - Use list coordinates to grab `2`, `13`, and `14` together.

<details>
<summary>💡 Need a hint?</summary>

- 3D coordinate target: `arr_3d[layer, row, col]`
- Slicing across all layers: `arr_3d[:, target_row, :]`
- Fancy indexing syntax: `arr[[row_indices], [col_indices]]`
</details>

Lets create the shape of `(2, 2, 2)` array

In [11]:
import numpy as np

a = np.array( [ [ [1,2],[3,4] ] , [ [5,6],[7,8] ] ] )
a

array([[[1, 2],
        [3, 4]],

       [[5, 6],
        [7, 8]]])

Retrieve the element `4`

In [12]:
a[0,1,1]

np.int64(4)

Extract the sub-blocks `[[3, 4]]` and `[[7, 8]]` across all depth layers

In [13]:
a[:,1,:]

array([[3, 4],
       [7, 8]])

Overwrite those selected blocks with `[[30, 40], [70, 80]]`

In [14]:
a[:,1,:] = [[30, 40], [70, 80]]
a

array([[[ 1,  2],
        [30, 40]],

       [[ 5,  6],
        [70, 80]]])

On the 2D array `sample = np.array([[1,2,3,4,5,6,7], [8,9,10,11,12,13,14]])`:
   - Use list coordinates to grab `2` and `13` simultaneously in one query.
   - Use list coordinates to grab `2`, `13`, and `14` together.

In [15]:
sample = np.array([[1,2,3,4,5,6,7], [8,9,10,11,12,13,14]])
print(sample)

print('------------')

print ( sample[ [0, 1] , [1, -2] ] )

print('------------')

print( sample[ [0, 1, 1] , [1, -2, -1] ] )

[[ 1  2  3  4  5  6  7]
 [ 8  9 10 11 12 13 14]]
------------
[ 2 13]
------------
[ 2 13 14]
