### Exercise 4: Matrix Generators & Sequence Initialization

**Requirements:**
Generate the following arrays without typing the numbers manually:
1. A `(2, 3)` grid populated entirely with zeros cast as 32-bit integers.
2. A `(2, 2)` grid populated entirely with ones.
3. A `(2, 2)` grid filled completely with the number `99`.
4. A `(2, 4)` grid of random continuous floating-point values between `0.0` and `1.0`.
5. A `(2, 4)` grid of random integers bounded between `2` and `10`.
6. An evenly spaced sequential array starting at `2` and ending before `20` with an increment step of `2`.
7. A `5x5` square matrix with ones on the main diagonal and zeros everywhere else.

<details>
<summary>💡 Need a hint?</summary>

- Zeros: `np.zeros(shape, dtype=...)`
- Ones: `np.ones(shape)`
- Fixed constant: `np.full(shape, fill_value)`
- Continuous uniform floats: `np.random.rand(rows, cols)`
- Discrete random integers: `np.random.randint(low, high, size=shape)`
- Stepped sequences: `np.arange(start, stop, step)`
- Identity square: `np.identity(n)`
</details>

Generate `(2, 3)` grid populated entirely with zeros cast as 32-bit integers

In [2]:
import numpy as np

a = np.zeros( (2, 3) , dtype='int32' )
a

array([[0, 0, 0],
       [0, 0, 0]], dtype=int32)

Generate `(2, 2)` grid populated entirely with ones

In [3]:
b = np.ones( (2, 2) )
b

array([[1., 1.],
       [1., 1.]])

Generate `(2, 2)` grid filled completely with the number `99`

In [4]:
c = np.full( (2, 2) , 99 )
c

array([[99, 99],
       [99, 99]])

Generate `(2, 4)` grid of random continuous floating-point values between `0.0` and `1.0`

In [5]:
d = np.random.rand(2,4)
d

array([[0.23717933, 0.82895918, 0.63424671, 0.76391657],
       [0.35118016, 0.39822789, 0.14907301, 0.54677758]])

Generate `(2, 4)` grid of random integers bounded between `2` and `10`

In [6]:
e = np.random.randint( 2, 10, (2,4))
e

array([[4, 7, 8, 5],
       [2, 3, 6, 8]], dtype=int32)

Generate an evenly spaced sequential array starting at `2` and ending before `20` with an increment step of `2`

In [7]:
f = np.arange(2, 20, 2)
f

array([ 2,  4,  6,  8, 10, 12, 14, 16, 18])

Generate a `5x5` square matrix with ones on the main diagonal and zeros everywhere else

In [8]:
g = np.identity(5)
g

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])