### Exercise 5: Problem Solving 1
#### Task 1: Concentric Framed Matrix
Construct the following 5x5 matrix using slice replacement:
```text
[[1, 1, 1, 1, 1],
 [1, 0, 0, 0, 1],
 [1, 0, 9, 0, 1],
 [1, 0, 0, 0, 1],
 [1, 1, 1, 1, 1]]
```

#### Task 2: 6x5 Grid Coordinate Slicing
Create a 6x5 matrix containing numbers `1` through `30`.
1. Extract the sub-grid: `[[11, 12], [16, 17]]`.
2. Extract the diagonal values `[2, 8, 14, 20]`.
3. Extract rows `0, 4, 5` with columns starting from index `3` to the end.

<details>
<summary>💡 Need a hint?</summary>

- For Task 1: Initialize a 5x5 array of ones, insert a 3x3 block of zeros into the center slice `1:4, 1:4`, then set center coordinate `[2, 2]` to 9.
- For Task 2: Build `np.arange(1, 31).reshape(6, 5)`.
  - Sub-grid: `grid[2:4, 0:2]`
  - Diagonal coordinates: `grid[[0, 1, 2, 3], [1, 2, 3, 4]]`
  - Mixed slice: `grid[[0, 4, 5], 3:]`
</details>

#### Task 1: Concentric Framed Matrix
Construct the following 5x5 matrix using slice replacement:
```text
[[1, 1, 1, 1, 1],
 [1, 0, 0, 0, 1],
 [1, 0, 9, 0, 1],
 [1, 0, 0, 0, 1],
 [1, 1, 1, 1, 1]]

In [2]:
import numpy as np

a = np.ones( (5,5) , dtype='int32')
a

array([[1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1]], dtype=int32)

In [4]:
b = np.zeros( (3, 3) , dtype='int32')
b

array([[0, 0, 0],
       [0, 0, 0],
       [0, 0, 0]], dtype=int32)

In [12]:
a[1:4, 1:4] = b
a

array([[1, 1, 1, 1, 1],
       [1, 0, 0, 0, 1],
       [1, 0, 0, 0, 1],
       [1, 0, 0, 0, 1],
       [1, 1, 1, 1, 1]], dtype=int32)

In [16]:
a[2, 2] = 9
a

array([[1, 1, 1, 1, 1],
       [1, 0, 0, 0, 1],
       [1, 0, 9, 0, 1],
       [1, 0, 0, 0, 1],
       [1, 1, 1, 1, 1]], dtype=int32)

#### Task 2: 6x5 Grid Coordinate Slicing
Create a 6x5 matrix containing numbers `1` through `30`.
1. Extract the sub-grid: `[[11, 12], [16, 17]]`.
2. Extract the diagonal values `[2, 8, 14, 20]`.
3. Extract rows `0, 4, 5` with columns starting from index `3` to the end.

In [20]:
a1 = np.arange(1,6,1)
print(a1)

a2 = np.arange(6,11,1)
print(a2)

a3 = np.arange(11,16,1)
print(a3)

a4 = np.arange(16,21,1)
print(a4)

a5 = np.arange(21,26,1)
print(a5)

a6 = np.arange(26,31,1)
print(a6)

[1 2 3 4 5]
[ 6  7  8  9 10]
[11 12 13 14 15]
[16 17 18 19 20]
[21 22 23 24 25]
[26 27 28 29 30]


In [22]:
b2 = np.vstack((a1,a2,a3,a4,a5,a6))
b2

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25],
       [26, 27, 28, 29, 30]])

1. Extract the sub-grid: `[[11, 12], [16, 17]]`.

In [24]:
b2[2:4, 0:2]

array([[11, 12],
       [16, 17]])

2. Extract the diagonal values `[2, 8, 14, 20]`.

In [27]:
b2[ [0, 1, 2, 3], [1, 2, 3, 4]]

array([ 2,  8, 14, 20])

3. Extract rows `0, 4, 5` with columns starting from index `3` to the end.

In [31]:
b2[[0, 4, 5], 3:]

array([[ 4,  5],
       [24, 25],
       [29, 30]])