### Exercise 6: Reference Traps & Vectorized Arithmetic

**Requirements:**
1. **Memory Referencing vs Deep Copy:**
   - Create `a = np.array([1, 2, 3])`.
   - Create an independent copy `b`.
   - Modify `b[0] = 100` and demonstrate that `a` remains unaffected.
2. **Vectorized Mathematical Operations:**
   - Take `v = np.array([1, 2, 3, 4])`.
   - Perform element-wise addition (+2), multiplication (*2), squaring, and sine calculation without loops.
   - Perform element-wise addition between `v` and `w = np.array([10, 20, 30, 40])`.

<details>
<summary>💡 Need a hint?</summary>

- Deep copy: `arr.copy()` (avoid direct pointer assignment `b = a`)
- Trigonometry: `np.sin(arr)`
- Vectorized array addition: `v + w`
</details>

------------------------------------------------

1. **Memory Referencing vs Deep Copy:**
   - Create `a = np.array([1, 2, 3])`.
   - Create an independent copy `b`.
   - Modify `b[0] = 100` and demonstrate that `a` remains unaffected.



In [1]:
import numpy as np

a = np.array([1, 2, 3])
print('a is: ', a)

a is:  [1 2 3]


In [2]:
b = a.copy()

print('b is: ', b)

b is:  [1 2 3]


In [4]:
b[0]  = 100

print('b is: ', b)
print('a is: ', a)

b is:  [100   2   3]
a is:  [1 2 3]


2. **Vectorized Mathematical Operations:**
   - Take `v = np.array([1, 2, 3, 4])`.
   - Perform element-wise addition (+2), multiplication (*2), squaring, and sine calculation without loops.
   - Perform element-wise addition between `v` and `w = np.array([10, 20, 30, 40])`.

In [8]:
v = np.array([1, 2, 3, 4])

print(v+2)

print(v*2)

print(np.sqrt(v))

print(np.sin(v))

[3 4 5 6]
[2 4 6 8]
[1.         1.41421356 1.73205081 2.        ]
[ 0.84147098  0.90929743  0.14112001 -0.7568025 ]


In [9]:
w = np.array([10, 20, 30, 40])

v+w

array([11, 22, 33, 44])