### Exercise 7: Arrray Reshaping & Stacking

**Requirements:**
1. Take `arr = np.array([[1,2,3,4],[5,6,7,8]])` (shape 2x4) and reorganize it into shapes `(4, 2)` and `(1, 8)`.
2. Take `a1 = np.array([1, 2, 3, 4])` and `a2 = np.array([5, 6, 7, 8])`:
   - Combine them vertically into a 2D matrix.
   - Combine them horizontally into a single 1D sequence.


<details>
<summary>💡 Need a hint?</summary>

- Reshape: `arr.reshape((rows, cols))`
- Vertical stack: `np.vstack([a1, a2])`
- Horizontal stack: `np.hstack([a1, a2])`
</details>

--------------------

1. Take `arr = np.array([[1,2,3,4],[5,6,7,8]])` (shape 2x4) and reorganize it into shapes `(4, 2)` and `(1, 8)`.

In [9]:
import numpy as np

arr = np.array([[1,2,3,4],[5,6,7,8]])

print(arr)

# Let's reshape into (4,2)
shape1 = arr.reshape((4,2))
print(shape1)


# Let's reshape into (1,8)
shape2 = arr.reshape((1,8))
print(shape2)

[[1 2 3 4]
 [5 6 7 8]]
[[1 2]
 [3 4]
 [5 6]
 [7 8]]
[[1 2 3 4 5 6 7 8]]


2. Take `a1 = np.array([1, 2, 3, 4])` and `a2 = np.array([5, 6, 7, 8])`:
   - Combine them vertically into a 2D matrix.
   - Combine them horizontally into a single 1D sequence.

In [10]:
a1 = np.array([1, 2, 3, 4])
a2 = np.array([5, 6, 7, 8])

vertical_stack= np.vstack((a1,a2))
print(vertical_stack)

horizontal_stack= np.hstack((a1,a2))
print(horizontal_stack)


[[1 2 3 4]
 [5 6 7 8]]
[1 2 3 4 5 6 7 8]
