### Exercise 9: Sorting, Conditional Locations & Extraction

**Requirements:**
1. Sort a 1D numerical array `[6, 7, 4, 9, 0, 2, 1]` in ascending order.
2. Sort a 2D matrix `[[6, 7, 1, 9], [8, 3, 5, 0]]` row-by-row.
3. Given `nums = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 3])`:
   - Find all index coordinates where values equal `3`.
   - Find all index coordinates where values are even.
   - Retrieve the actual matching even numbers using those coordinates.

<details>
<summary>💡 Need a hint?</summary>

- Sort: `np.sort(array)`
- Conditional search: `locs = np.where(condition)`
- Unpack indices: `locs[0]`
- Extract using indices: `nums[locs[0]]`
- Even condition: `nums % 2 == 0`
</details>

----------

1. Sort a 1D numerical array `[6, 7, 4, 9, 0, 2, 1]` in ascending order.

In [15]:
import numpy as np

arr = np.array([6, 7, 4, 9, 0, 2, 1])

sorted_array = np.sort(arr)
print(sorted_array)

[0 1 2 4 6 7 9]


2. Sort a 2D matrix `[[6, 7, 1, 9], [8, 3, 5, 0]]` row-by-row.

In [16]:
arr2 = np.array([[6, 7, 1, 9], [8, 3, 5, 0]])

sorted_array2 = np.sort(arr2, axis=1)
print(sorted_array2)

[[1 6 7 9]
 [0 3 5 8]]


3. Given `nums = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 3])`:
   - Find all index coordinates where values equal `3`.
   - Find all index coordinates where values are even.
   - Retrieve the actual matching even numbers using those coordinates.

   - Find all index coordinates where values equal `3`.

In [17]:
nums = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 3])

np.where(nums==3)

(array([ 2, 10]),)

   - Find all index coordinates where values are even.

In [18]:
nums = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 3])

a1 = np.where(nums%2==0)

   - Retrieve the actual matching even numbers using those coordinates.

In [19]:
print(a1)   # The values are in a tuble so let's take it out

print(a1[0])

# LEt's call the indexes of nums array
nums[a1[0]]



(array([1, 3, 5, 7, 9]),)
[1 3 5 7 9]


array([ 2,  4,  6,  8, 10])